#!/usr/bin/env python3
"""PreToolUse hook: block hand-edits to tool-owned files.

Blocks: any markdown whose devkit marker says `generated` (TASKS.md, traceability.md,
workspace README.md, decision-log.md) and every tracker data file (tasks.json in a
workspace's 03-delivery/ or legacy flat layout, decision-log.json).
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
from devkit_common import read_marker  # noqa: E402

OWNERS = {"board": "tracker.py", "traceability": "tracker.py trace", "index": "scaffold.py index",
          "decision-log": "adr.py scan", "readiness": "review.py readiness"}

try:
    payload = json.load(sys.stdin)
except json.JSONDecodeError:
    sys.exit(0)
path = Path(str(payload.get("tool_input", {}).get("file_path", "")))
doc_type, generated = read_marker(path) if path.suffix == ".md" and path.exists() else (None, False)
owner = None
if generated:
    owner = OWNERS.get(doc_type, "its devkit tool")
elif path.name == "tasks.json" and (path.parent.name == "03-delivery" or "specs" in path.parts):
    owner = "tracker.py (add/import/update/start/done/block)"
elif path.name == "decision-log.json":
    owner = "adr.py scan"
if owner:
    print(f"{path.name} is generated by devkit — change it through `python3 devkit/tools/{owner}`, "
          "not by editing the file.", file=sys.stderr)
    sys.exit(2)
